### ISSUE TITLE
no possibility to provide encrypted key (feature request)

### ISSUE THREAD

**Issue by Justinemmerich** [mulesoft-consulting/jwt-module#2]
**Actual:**
works only with decrypted keys 

**Expected:**
possibility to use encrypted keys

maybe this can help to get the implementation done [stackoverflow read-an-encrypted-private-key-with-bouncycastle-spongycastle](https://stackoverflow.com/questions/22920131/read-an-encrypted-private-key-with-bouncycastle-spongycastle)

**Comment by cajhughes** [comment]
Hi @Justinemmerich,
Thanks for this suggestion - while I can't guarantee any time-frame for this enhancement, I will look to incorporate this functionality in a future release.
Thanks!

**Comment by Justinemmerich** [comment]
Hey chris, 

I created already an enhancement, and some testcases, but this is not yet 100% ready, but I could publish this in a feature branch If you like, so you could give me some Guidance 

⁣BlueMail for Android herunterladen ​

Am 11. März 2022, 14:18, um 14:18, Chris Hughes ***@***.***> schrieb:
>Hi @Justinemmerich,
>Thanks for this suggestion - while I can't guarantee any time-frame for
>this enhancement, I will look to incorporate this functionality in a
>future release.
>Thanks!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mulesoft-consulting/jwt-module/issues/2#issuecomment-1065105555
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by cajhughes** [comment]
Hi @Justinemmerich,
I have added preliminary support for encrypted keys in release 0.6.0. Can you please test with this release and let me know if you observe any problems?
Many thanks!

**Comment by cajhughes** [comment]
Closing this issue as support included in 0.6.0 release.
